---
title: "best-sbp-portfolio new"
output: html_document
---

```{r}
suppressPackageStartupMessages(library(tidyquant))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(timetk))
library(PortfolioAnalytics)
```


```{r, cache=TRUE}

spb_tickers <- read.csv("tickers-spb.csv")
spb_tickers <- spb_tickers[,2]
spb_tickers <- gsub("@", ".", spb_tickers)
not_available <- c("APPS", "EPAM")
spb_tickers <- spb_tickers[!spb_tickers %in% not_available]


price_from <- "2017-11-19"
price_to <- "2020-11-19"

price_data <- tq_get(spb_tickers,
                     from = price_from,
                     to = price_to,
                     get = 'stock.prices')

# my brocker doesn't have


price_data_cheap_idx <- price_data %>%
    group_by(symbol) %>%
    mutate(last = last(close)) %>%
    summarize(lastdate = max(date), 
              lastprice = max(last), .groups = "drop") %>%
    filter(lastprice <= 80)

price_data_cheap <- price_data %>%
    filter(symbol %in% price_data_cheap_idx$symbol)


log_ret_tidy <- price_data_cheap %>%
    group_by(symbol) %>%
    tq_transmute(select = adjusted,
                 mutate_fun = periodReturn,
                 period = 'daily',
                 col_rename = 'ret',
                 type = 'log')

log_ret_xts <- log_ret_tidy %>%
        pivot_wider(names_from = symbol, values_from = ret) %>%
        tk_xts(silent = T)

trade_begin <- as.Date(sapply(log_ret_xts, function(x){
    if(!any(is.na(log_ret_xts))){
        min(index(x))
    }else{
        index(log_ret_xts)[min(which(!is.na(x)))]
    }
}))

log_ret_xts <- log_ret_xts[,-which(trade_begin > today()-years(2))]
nrow(log_ret_xts)
ncol(log_ret_xts)

chunks <- stackoverflow::chunk2(names(log_ret_xts), 10)
combinations <- expand.grid(chunks[1:2])
```


```{r}
set.seed(9)
num_fit <- 100000000
sharpe_ratio_fit <- 0
sharpe_ratio_fit_best <- sharpe_ratio_fit
cnt_tries <- 0
cnt_info <- 0
cnt_total <- 0
risk_free <- 0
start_fit <- Sys.time()

# Construct initial portfolio


while(cnt_tries <= num_fit){
    s <- Sys.time()
    cnt_tries <- cnt_tries + 1
    cnt_info <- cnt_info + 1
    tmp_tickers_idx <- sample(ncol(log_ret_xts), 10)
    tmp_tickers <- names(log_ret_xts)[tmp_tickers_idx]
    log_ret_xts_tmp <- log_ret_xts[,tmp_tickers]
    log_ret_xts_tmp <- na.omit(log_ret_xts_tmp)
    nrow(log_ret_xts_tmp)
    ##
    init.portf <- portfolio.spec(assets=colnames(log_ret_xts_tmp))
    init.portf <- add.constraint(portfolio=init.portf, type="full_investment")
    init.portf <- add.constraint(portfolio=init.portf, type="long_only")
    init.portf <- add.objective(portfolio=init.portf, 
                                type="return", name="mean")
    init.portf <- add.objective(portfolio=init.portf, 
                                type="risk", name="StdDev")
    #init.portf 

    
    maxSR.lo.ROI <- optimize.portfolio(R = log_ret_xts_tmp, 
                                       portfolio = init.portf, 
                                       optimize_method = "ROI", 
                                       maxSR = TRUE, trace = TRUE)
    
   
    port_mean <- maxSR.lo.ROI$objective_measures$mean
    port_sd <- maxSR.lo.ROI$objective_measures$StdDev
   
   # maxSRReturns <- Return.portfolio(log_ret_xts_tmp, 
    #                               weight = extractWeights(maxSR.lo.ROI), 
     #                              rebalance_on = "days")
    
    #table.AnnualizedReturns(R = maxSRReturns)
    
    port_return <- log_ret_xts_tmp %*% as.numeric(maxSR.lo.ROI$weights)
    port_return <- prod(port_return + 1)^(252/nrow(port_return)) - 1
    
    cov_mat <- cov(log_ret_xts_tmp) * 252
    port_risk <- sqrt(t(as.numeric(maxSR.lo.ROI$weights)) %*% (cov_mat %*% as.numeric(maxSR.lo.ROI$weights)))
    
    f <- Sys.time()
    difftime(f,s)

    
    # Creating and storing Portfolio Sharpe Ratios
    
    sr <- as.numeric(port_return / port_risk)
    #table.AnnualizedReturns(R = maxSRReturns, Rf = risk_free/252)
    
    if(sr >= 0){
        from <- min(index(log_ret_xts_tmp))
        to <- max(index(log_ret_xts_tmp))
        best_tickers_comb <- tmp_tickers 
        port_fit_returns <- round(port_return,3)
        port_fit_risk <- round(port_sd,3)
        sharpe_ratio_fit <- round(sr,3)
        fit_portfolio_values <- data.frame(
            Return = port_fit_returns,
            Risk = port_fit_risk,
            SharpeRatio = sharpe_ratio_fit)
        
        wts_fit <- data.frame(t(round(extractWeights(maxSR.lo.ROI), 2)))
        #colnames(wts_fit) <- best_tickers_comb
        fit_portfolio_values <- cbind(wts_fit, fit_portfolio_values)
        p <- fit_portfolio_values %>%
            gather(names(fit_portfolio_values)[1]:names(fit_portfolio_values)[length(names(fit_portfolio_values))-3], 
                   key = Asset,
                   value = Weights) %>%
            mutate(Asset = as.factor(Asset)) %>%
            ggplot(aes(x = fct_reorder(Asset,Weights), 
                       y = Weights, fill = Asset)) +
            geom_bar(stat = 'identity') +
            geom_text(aes(x = fct_reorder(Asset,Weights), y = Weights,
                          label = Weights), 
                      nudge_y = 0.015, color = "gray 30") +
            theme_minimal() +
            labs(x = 'Assets', 
                 y = 'Weights', 
                 title = "Current optimal portfolio",
                 subtitle = paste("From:", from, "to", to,
                                  "| SR:", as.numeric(sharpe_ratio_fit),
                                  "| Return:", port_fit_returns,
                                  "| Risk: ", port_fit_risk)) +
            scale_y_continuous(labels = scales::percent)
        filesave <- paste0("spb-portfolios\\portfolio","_sr",
               gsub("\\.", "\\_", as.character(sharpe_ratio_fit)),
               "_", cnt_total,".png")
        #ggsave(filesave,p, width=8, height=5)
        print(p)
    }
    
    
    if(round(sr,3) > sharpe_ratio_fit_best){
        sharpe_ratio_fit_best <- round(sr,3)
        cnt_tries <- 0
        cnt_info <- 0
        wts_fit <- round(extractWeights(maxSR.lo.ROI),2)

        time_past <- round(difftime(Sys.time(), start_fit, 
                                    units = "hours"), 2)
        cat("\014" ,"Sharpe ratio: ",sharpe_ratio_fit_best,
            "| Time past: ", time_past, "hours", 
            "Num try:", cnt_total, "\r")
        print(p)
    }
    if(cnt_info == 100){
        cnt_info <- 0
        time_past <- round(difftime(Sys.time(), start_fit, 
                                    units = "hours"), 2)
        cat("\014", "Tries: ", cnt_tries/1000000, " M", 
            "| Sharpe ratio: ", sharpe_ratio_fit_best, 
            "| Time past: ", time_past, "hours", "\r")
    }
    cnt_total <- cnt_total + 1
}


finish_fit <- Sys.time()
spent <- difftime(finish_fit, start_fit, units = "mins")
spent

# Converting matrix to a tibble and changing column names
wts_fit <- as_tibble(rbind(wts_fit))
colnames(wts_fit) <- best_tickers_comb

# Combing all the values together
fit_portfolio_values <- tk_tbl(cbind(wts_fit, fit_portfolio_values), preserve_index = F)
```
